### ISSUE TITLE
HTTP/1.1 204 No Content

### ISSUE THREAD

**Issue by shersch** [kernelkaribou/synology-monitoring#8]
After much tinkering and tweaking, I finally got this running, but I keep getting this HTTP/1.1 204 No Content error, and I'm not entirely sure why.  It's by no means a deal breaker, and I can't even tell what's wrong, but I know it'll keep me up at night.  Hoping you can chime in and tell me what's going on.  Thanks in advance!

```
Capturing 3 times
Skipping UPS capture
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1898    0     0  100  1898      0   4466 --:--:-- --:--:-- --:--:--  4476
HTTP/1.1 100 Continue

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 881972bb-1a20-11ea-8170-0242ac110002
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.9
X-Request-Id: 881972bb-1a20-11ea-8170-0242ac110002
Date: Mon, 09 Dec 2019 01:09:21 GMT
```

**Comment by kernelkaribou** [comment]
Hello @shersch.  This should be valid as 204 is basically saying it processed the request but there was no return response beyond the 204.  Where it could become an issue is if you are not seeing the data written, which if it is then that would be the expected behavior.

Write to Influx, if successful return a 204 AND data is visible in the database.
